spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?useSSL=true&requireSSL=true&verifyServerCertificate=false
    username:  ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: ${MAIL_HOST:smtp-relay.brevo.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:90ed92001@smtp-brevo.com}
    password: ${MAIL_PASSWORD:j5gPD06Xn7AaNwFT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          from: ${MAIL_FROM:ragulpant411@gmail.com}

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  servlet:
    context-path: /api/v1.0

jwt:
  secret:
    key: ${SECRET_KEY:thisisthesecretkeyievercreatedinmydevelopmentcareer}
